/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary":                    "#3d007d",
        "primary-container":          "#552299",
        "primary-fixed":              "#ecdcff",
        "primary-fixed-dim":          "#d6baff",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "#c39bff",
        "on-primary-fixed":           "#280056",
        "on-primary-fixed-variant":   "#5a299e",
        "secondary":                  "#685684",
        "secondary-container":        "#dfc8fd",
        "secondary-fixed":            "#ecdcff",
        "secondary-fixed-dim":        "#d3bdf2",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "#63517f",
        "on-secondary-fixed":         "#23123c",
        "on-secondary-fixed-variant": "#503e6a",
        "surface":                    "#faf9fc",
        "surface-dim":                "#dbd9dd",
        "surface-bright":             "#faf9fc",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f5f3f7",
        "surface-container":          "#efedf1",
        "surface-container-high":     "#e9e7eb",
        "surface-container-highest":  "#e3e2e6",
        "surface-variant":            "#e3e2e6",
        "on-surface":                 "#1b1b1e",
        "on-surface-variant":         "#4a4452",
        "on-background":              "#1b1b1e",
        "background":                 "#faf9fc",
        "outline":                    "#7c7483",
        "outline-variant":            "#cdc3d4",
        "inverse-surface":            "#303033",
        "inverse-on-surface":         "#f2f0f4",
        "inverse-primary":            "#d6baff",
        "surface-tint":               "#7344b8",
        "error":                      "#ba1a1a",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "on-error-container":         "#93000a",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Inter",   "sans-serif"],
        label:    ["Inter",   "sans-serif"],
      },
    },
  },
  plugins: [],
};
